table Age
	lineageTag: d0dfd344-2155-483d-8fe2-2fd3caed3919

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 1ac2e863-7cfe-49a7-84ec-fa46635bc0e7
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column 'Age Bucket'
		dataType: string
		lineageTag: fb95e3e6-64f2-4cde-a500-35e8306d2183
		summarizeBy: none
		sourceColumn: Age Bucket

		annotation SummarizationSetBy = Automatic

	partition Age-3e4824bd-a87e-4e01-bfbf-166592b94c64 = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("dc8rDsAgEIThqxA0AnZZHmchCER1k7amty+gaMKYEZ/6pxTtRJs+6jkVWfUe7bp1Nd0D8Ag8Ac97JwvcdSc3XVYn4AzcAxfg4y+F4fzricAT8Lx3tsDHX549vPYwAWfgHrhsvH4=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [Age = _t, #"Age Bucket" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Age", Int64.Type}, {"Age Bucket", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

