table Association
	lineageTag: 6ca4907e-c8c9-4e62-ba5d-df131c88764f

	column RuleID
		dataType: int64
		formatString: 0
		lineageTag: c2de41e2-24af-4a2c-b0b2-f4b46528da58
		summarizeBy: count
		sourceColumn: RuleID

		annotation SummarizationSetBy = Automatic

	column LeftItemSetId
		dataType: int64
		formatString: 0
		lineageTag: 83bf79f6-a4ea-488e-9650-431cc9c8053b
		summarizeBy: none
		sourceColumn: LeftItemSetId

		annotation SummarizationSetBy = Automatic

	column RightItemSetId
		dataType: int64
		formatString: 0
		lineageTag: 0392cdb4-d1c7-472b-8306-104f0d062921
		summarizeBy: none
		sourceColumn: RightItemSetId

		annotation SummarizationSetBy = Automatic

	column Probability
		dataType: double
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 33cd36b2-a57d-4705-8a33-54d3e7cab3d1
		summarizeBy: sum
		sourceColumn: Probability

		annotation SummarizationSetBy = Automatic

	column Importance
		dataType: double
		lineageTag: 825fdc95-b217-48c0-8cc3-07079ad178c5
		summarizeBy: sum
		sourceColumn: Importance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Support
		dataType: int64
		formatString: 0
		lineageTag: 164305ab-babd-4a89-9044-36c03cea0457
		summarizeBy: sum
		sourceColumn: Support

		annotation SummarizationSetBy = Automatic

	partition Association-7d9865cc-e0f7-465e-8a07-5176d6094e2a = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\mimyersm\Dropbox\Data-27-09-2019.xlsx"), null, true),
				    Association_Sheet = Source{[Item="Association",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Association_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"RuleID", Int64.Type}, {"LeftItemSetId", Int64.Type}, {"RightItemSetId", Int64.Type}, {"Probability", type number}, {"Importance", type number}, {"Support", Int64.Type}}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Changed Type", "Merged", each Text.Combine({Text.From([LeftItemSetId], "en-CA"), Text.From([RightItemSetId], "en-CA")}, ""), type text),
				    #"Removed Duplicates" = Table.Distinct(#"Inserted Merged Column", {"Merged"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Removed Duplicates",{"Merged"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

