table Calendar
	lineageTag: 715a3f9c-bea5-4323-948a-10b6ce711619

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b43e6592-f612-4ac5-9429-486c04ef5db6
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 677d2c0d-f04e-4bfb-ab65-d6e85634f934
			defaultHierarchy: LocalDateTable_d9fbe243-4814-4038-8eec-593e864a563b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Month
		dataType: string
		lineageTag: f704eb5c-79ae-4176-9512-73d288c64e69
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: MonthSort

		annotation SummarizationSetBy = Automatic

	column MonthSort
		dataType: int64
		formatString: 0
		lineageTag: 03c64f84-4a10-4a58-b685-edbedab1bbcf
		summarizeBy: sum
		sourceColumn: MonthSort

		annotation SummarizationSetBy = Automatic

	column Week
		dataType: int64
		formatString: 0
		lineageTag: 689a2d9e-aef3-4ed5-b3f6-0861ebe9ce73
		summarizeBy: sum
		sourceColumn: Week

		annotation SummarizationSetBy = Automatic

	column Empty = ""
		lineageTag: b95bebd9-1156-475f-9561-268b1c226fa9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Calendar-e63c2b10-f169-4be4-bbe5-8ec70193c03b = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("fZSxisMwDIZfJWQuqSQ7dtztlg6FPkHpkIMbrxyFG+7tq4vcwD9I4IQUvg/kfk5ut5H4qEuI28ByItI1rNPwPY2HkfW6rI/+xOP9oHzxeQFeNp6Tzyfg08YL+XwGPhtffX4Gfrb5dR5x+KLX+euz76TY/OTzFfhqfPX5BfjF5s8+34Bv+/zJ60V6u67P/tfqz/cOXIPR4H0PriFoyL4L10hoWOfEgZHRsNKkU2XP+E/98fPsh4StNefAKGhYbeHAqGhYb1kCY0HDitN81OUYbdv5Xz+8bM1ZfEMIDOnNW2AwGtZcSmAIGtZcj61+DBxje7V/H/2lEmtOLTAyGtacS2DMaFhzSYFR0LDmiQKjoqHN7y8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [Date = _t, Week = _t, #"Month Name" = _t, MonthSort = _t, #"Week of Year" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Date", type datetime}, {"Week", Int64.Type}, {"Month Name", type text}, {"MonthSort", Int64.Type}, {"Week of Year", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Month Name", "Month"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"Week of Year"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

