table 'Issues and Promotions'
	lineageTag: bfc7c642-2029-4822-8fa6-e2079db05177

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 5ce394e9-c549-491a-9d43-577808c95b6f
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Issue
		dataType: string
		lineageTag: 4e76d946-7718-46a1-b20e-9e4eff83406c
		summarizeBy: none
		sourceColumn: Issue

		annotation SummarizationSetBy = Automatic

	column Promotion
		dataType: string
		lineageTag: 18afb55e-bc69-4fbd-acb5-eb654adf78de
		summarizeBy: none
		sourceColumn: Promotion

		annotation SummarizationSetBy = Automatic

	partition 'Issues and Promotions-4fcca441-ca28-47a0-ade9-7ea141432e0e' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\mimyersm\Desktop\Sales & Marketing Datas.xlsx"), null, true),
				    #"Issues and Promotions_Sheet" = Source{[Item="Issues and Promotions",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Issues and Promotions_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"Issue", type text}, {"Promotion", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

